[package]
name = "raft"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trust-dns-client = "0.22.0"
resolv-conf = "0.7.0"
random-access-disk = "0.8.0"