CREATE TABLE TABLE1
(
  ID  NUMBER GENERATED BY DEFAULT AS IDENTITY
, TXT VARCHAR2(200 BYTE)
, CONSTRAINT TABLE1_PK PRIMARY KEY
  (
    ID
  )
)
;

insert into table1 (txt) values ('line 1');
insert into table1 (txt) values ('line 2');
insert into table1 (txt) values ('line 3');
insert into table1 (txt) values ('line 4');
commit;