alter session set "_ORACLE_SCRIPT"=true;

-- USER SQL
CREATE USER "TESTNOTIFY" IDENTIFIED BY "TESTNOTIFY"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER "TESTNOTIFY" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "TESTNOTIFY" ;
GRANT "RESOURCE" TO "TESTNOTIFY" ;
ALTER USER "TESTNOTIFY" DEFAULT ROLE "CONNECT","RESOURCE";

-- SYSTEM PRIVILEGES
GRANT CHANGE NOTIFICATION TO "TESTNOTIFY" ;

